name: CI/CD for Python Project

on:
  push:
    branches:
      - NB-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/new-branch-name'
        run: |
          # Your deployment script or command here
          # For example, deploying to a staging server
          echo "Deploying to staging..."
          ssh user@staging-server "cd /path/to/project && git pull origin new-branch-name && python manage.py migrate && python manage.py collectstatic --noinput && sudo systemctl restart your-app"
